[artf1265060][25Q4_AUTO]: Fix -Wignored-attributes warning
Void does not need an attribute saying it is unused so just remove it

packages/modules/Nfc/libnfc-nci/tests/src/nfa_sys_cback_test.cc:22:42:

error: attribute 'unused' cannot be applied to a 'void' parameter

[-Werror,-Wignored-attributes]

   22 | static void mock_callback(__attribute__((unused)) void) {}

      |                                          ^~~~~~

1 error generated.

Flag: EXEMPT warning fix

Bug: 430598176

Test: m

out/soong/.intermediates/packages/modules/Nfc/libnfc-nci/tests/libnfc-nci-tests/android_x86_x86_64/obj/packages/modules/Nfc/libnfc-nci/tests/src/nfa_sys_cback_test.o